export type GpuSeed = {
  slug: string;
  name: string;
  shortName: string;
  architecture:
    | "blackwell"
    | "hopper"
    | "ada_lovelace"
    | "ampere"
    | "turing"
    | "volta"
    | "consumer_blackwell";
  vramGb: number;
  memoryType: string;
  generationYear?: number;
  isDatacenter?: boolean;
  isConsumer?: boolean;
};

export type ProviderSeed = {
  slug: string;
  name: string;
  displayName: string;
  providerType:
    | "specialized_neocloud"
    | "hyperscaler"
    | "regional_cloud"
    | "marketplace"
    | "depin"
    | "bare_metal";
  reliabilityTier: "enterprise" | "standard" | "community";
  websiteUrl: string;
  pricingUrl?: string;
  docsUrl?: string;
  hasPublicApi?: boolean;
  supportsSpot?: boolean;
  supportsReserved?: boolean;
  availableRegions?: string[];
  affiliateUrl?: string;
};

export const GPU_SEED: GpuSeed[] = [
  {
    slug: "b200-sxm",
    name: "NVIDIA B200 SXM",
    shortName: "B200",
    architecture: "blackwell",
    vramGb: 192,
    memoryType: "HBM3e",
    generationYear: 2024,
    isDatacenter: true,
  },
  {
    slug: "gb200-nvl",
    name: "NVIDIA GB200 NVL72",
    shortName: "GB200",
    architecture: "blackwell",
    vramGb: 192,
    memoryType: "HBM3e",
    generationYear: 2024,
    isDatacenter: true,
  },
  {
    slug: "h200-sxm",
    name: "NVIDIA H200 SXM",
    shortName: "H200",
    architecture: "hopper",
    vramGb: 141,
    memoryType: "HBM3e",
    generationYear: 2024,
    isDatacenter: true,
  },
  {
    slug: "h100-sxm",
    name: "NVIDIA H100 SXM",
    shortName: "H100 SXM",
    architecture: "hopper",
    vramGb: 80,
    memoryType: "HBM3",
    generationYear: 2023,
    isDatacenter: true,
  },
  {
    slug: "h100-pcie",
    name: "NVIDIA H100 PCIe",
    shortName: "H100 PCIe",
    architecture: "hopper",
    vramGb: 80,
    memoryType: "HBM3",
    generationYear: 2023,
    isDatacenter: true,
  },
  {
    slug: "a100-80gb",
    name: "NVIDIA A100 80GB",
    shortName: "A100 80GB",
    architecture: "ampere",
    vramGb: 80,
    memoryType: "HBM2e",
    generationYear: 2021,
    isDatacenter: true,
  },
  {
    slug: "a100-40gb",
    name: "NVIDIA A100 40GB",
    shortName: "A100 40GB",
    architecture: "ampere",
    vramGb: 40,
    memoryType: "HBM2e",
    generationYear: 2020,
    isDatacenter: true,
  },
  {
    slug: "l40s",
    name: "NVIDIA L40S",
    shortName: "L40S",
    architecture: "ada_lovelace",
    vramGb: 48,
    memoryType: "GDDR6",
    generationYear: 2023,
    isDatacenter: true,
  },
  {
    slug: "l4",
    name: "NVIDIA L4",
    shortName: "L4",
    architecture: "ada_lovelace",
    vramGb: 24,
    memoryType: "GDDR6",
    generationYear: 2023,
    isDatacenter: true,
  },
  {
    slug: "t4",
    name: "NVIDIA T4",
    shortName: "T4",
    architecture: "turing",
    vramGb: 16,
    memoryType: "GDDR6",
    generationYear: 2018,
    isDatacenter: true,
  },
  {
    slug: "a10g",
    name: "NVIDIA A10G",
    shortName: "A10G",
    architecture: "ampere",
    vramGb: 24,
    memoryType: "GDDR6",
    generationYear: 2021,
    isDatacenter: true,
  },
  {
    slug: "a40",
    name: "NVIDIA A40",
    shortName: "A40",
    architecture: "ampere",
    vramGb: 48,
    memoryType: "GDDR6",
    generationYear: 2020,
    isDatacenter: true,
  },
  {
    slug: "v100-16gb",
    name: "NVIDIA V100 16GB",
    shortName: "V100",
    architecture: "volta",
    vramGb: 16,
    memoryType: "HBM2",
    generationYear: 2017,
    isDatacenter: true,
  },
  {
    slug: "rtx-3090",
    name: "NVIDIA GeForce RTX 3090",
    shortName: "RTX 3090",
    architecture: "ampere",
    vramGb: 24,
    memoryType: "GDDR6X",
    generationYear: 2020,
    isDatacenter: false,
    isConsumer: true,
  },
  {
    slug: "rtx-4090",
    name: "NVIDIA GeForce RTX 4090",
    shortName: "RTX 4090",
    architecture: "ada_lovelace",
    vramGb: 24,
    memoryType: "GDDR6X",
    generationYear: 2022,
    isDatacenter: false,
    isConsumer: true,
  },
  {
    slug: "rtx-5090",
    name: "NVIDIA GeForce RTX 5090",
    shortName: "RTX 5090",
    architecture: "consumer_blackwell",
    vramGb: 32,
    memoryType: "GDDR7",
    generationYear: 2025,
    isDatacenter: false,
    isConsumer: true,
  },
];

export const PROVIDER_SEED: ProviderSeed[] = [
  {
    slug: "lambda-labs",
    name: "Lambda Labs",
    displayName: "Lambda",
    providerType: "specialized_neocloud",
    reliabilityTier: "enterprise",
    websiteUrl: "https://lambdalabs.com",
    pricingUrl: "https://lambdalabs.com/service/gpu-cloud",
    hasPublicApi: true,
    supportsSpot: false,
  },
  {
    slug: "coreweave",
    name: "CoreWeave",
    displayName: "CoreWeave",
    providerType: "specialized_neocloud",
    reliabilityTier: "enterprise",
    websiteUrl: "https://coreweave.com",
    hasPublicApi: true,
    supportsSpot: false,
  },
  {
    slug: "runpod",
    name: "RunPod",
    displayName: "RunPod",
    providerType: "marketplace",
    reliabilityTier: "standard",
    websiteUrl: "https://www.runpod.io",
    hasPublicApi: true,
    supportsSpot: true,
  },
  {
    slug: "vast-ai",
    name: "Vast.ai",
    displayName: "Vast.ai",
    providerType: "depin",
    reliabilityTier: "community",
    websiteUrl: "https://vast.ai",
    hasPublicApi: true,
    supportsSpot: true,
  },
  {
    slug: "io-net",
    name: "io.net",
    displayName: "io.net",
    providerType: "depin",
    reliabilityTier: "community",
    websiteUrl: "https://io.net",
    hasPublicApi: true,
    supportsSpot: true,
  },
  {
    slug: "salad",
    name: "Salad",
    displayName: "Salad",
    providerType: "depin",
    reliabilityTier: "community",
    websiteUrl: "https://salad.com",
    hasPublicApi: true,
    supportsSpot: true,
  },
  {
    slug: "nebius",
    name: "Nebius",
    displayName: "Nebius",
    providerType: "regional_cloud",
    reliabilityTier: "standard",
    websiteUrl: "https://nebius.com",
    hasPublicApi: true,
  },
  {
    slug: "gmi-cloud",
    name: "GMI Cloud",
    displayName: "GMI",
    providerType: "regional_cloud",
    reliabilityTier: "standard",
    websiteUrl: "https://gmicloud.ai",
    hasPublicApi: true,
  },
  {
    slug: "hyperstack",
    name: "Hyperstack",
    displayName: "Hyperstack",
    providerType: "regional_cloud",
    reliabilityTier: "standard",
    websiteUrl: "https://hyperstack.cloud",
    hasPublicApi: true,
  },
  {
    slug: "scaleway",
    name: "Scaleway",
    displayName: "Scaleway",
    providerType: "regional_cloud",
    reliabilityTier: "standard",
    websiteUrl: "https://www.scaleway.com",
    hasPublicApi: true,
  },
  {
    slug: "tensordock",
    name: "TensorDock",
    displayName: "TensorDock",
    providerType: "marketplace",
    reliabilityTier: "standard",
    websiteUrl: "https://tensordock.com",
    hasPublicApi: true,
  },
  {
    slug: "voltage-park",
    name: "Voltage Park",
    displayName: "Voltage Park",
    providerType: "specialized_neocloud",
    reliabilityTier: "enterprise",
    websiteUrl: "https://voltagepark.com",
    hasPublicApi: true,
  },
  {
    slug: "aws",
    name: "Amazon Web Services",
    displayName: "AWS",
    providerType: "hyperscaler",
    reliabilityTier: "enterprise",
    websiteUrl: "https://aws.amazon.com",
    hasPublicApi: true,
  },
  {
    slug: "gcp",
    name: "Google Cloud",
    displayName: "GCP",
    providerType: "hyperscaler",
    reliabilityTier: "enterprise",
    websiteUrl: "https://cloud.google.com",
    hasPublicApi: true,
  },
  {
    slug: "azure",
    name: "Microsoft Azure",
    displayName: "Azure",
    providerType: "hyperscaler",
    reliabilityTier: "enterprise",
    websiteUrl: "https://azure.microsoft.com",
    hasPublicApi: true,
  },
  {
    slug: "paperspace",
    name: "Paperspace",
    displayName: "Paperspace",
    providerType: "marketplace",
    reliabilityTier: "standard",
    websiteUrl: "https://www.paperspace.com",
    hasPublicApi: true,
  },
  {
    slug: "digitalocean",
    name: "DigitalOcean",
    displayName: "DigitalOcean",
    providerType: "regional_cloud",
    reliabilityTier: "standard",
    websiteUrl: "https://www.digitalocean.com",
    hasPublicApi: true,
  },
  {
    slug: "linode",
    name: "Linode (Akamai)",
    displayName: "Linode",
    providerType: "regional_cloud",
    reliabilityTier: "standard",
    websiteUrl: "https://www.linode.com",
    hasPublicApi: true,
  },
  {
    slug: "ovhcloud",
    name: "OVHcloud",
    displayName: "OVHcloud",
    providerType: "bare_metal",
    reliabilityTier: "standard",
    websiteUrl: "https://www.ovhcloud.com",
    hasPublicApi: false,
  },
  {
    slug: "latitude-sh",
    name: "Latitude.sh",
    displayName: "Latitude",
    providerType: "bare_metal",
    reliabilityTier: "standard",
    websiteUrl: "https://www.latitude.sh",
    hasPublicApi: false,
  },
  {
    slug: "vultr",
    name: "Vultr",
    displayName: "Vultr",
    providerType: "bare_metal",
    reliabilityTier: "standard",
    websiteUrl: "https://www.vultr.com",
    hasPublicApi: true,
  },
  {
    slug: "oracle-cloud",
    name: "Oracle Cloud Infrastructure",
    displayName: "OCI",
    providerType: "hyperscaler",
    reliabilityTier: "enterprise",
    websiteUrl: "https://www.oracle.com/cloud",
    hasPublicApi: true,
  },

  // Seed expansion toward 40+ providers (docs/migrations/003_seed_expansion.sql)
  {
    slug: "jarvis-labs",
    name: "Jarvis Labs",
    displayName: "Jarvis",
    providerType: "specialized_neocloud",
    reliabilityTier: "standard",
    websiteUrl: "https://jarvislabs.ai",
    pricingUrl: "https://jarvislabs.ai/pricing",
    hasPublicApi: true,
    supportsSpot: true,
  },
  {
    slug: "genesis-cloud",
    name: "Genesis Cloud",
    displayName: "Genesis",
    providerType: "regional_cloud",
    reliabilityTier: "standard",
    websiteUrl: "https://genesiscloud.com",
    pricingUrl: "https://genesiscloud.com/pricing",
    docsUrl: "https://docs.genesiscloud.com",
    hasPublicApi: false,
  },
  {
    slug: "ibm-cloud",
    name: "IBM Cloud",
    displayName: "IBM Cloud",
    providerType: "hyperscaler",
    reliabilityTier: "enterprise",
    websiteUrl: "https://www.ibm.com/cloud",
    pricingUrl: "https://www.ibm.com/cloud/pricing",
    docsUrl: "https://cloud.ibm.com/docs",
    hasPublicApi: true,
    supportsReserved: true,
  },

  {
    slug: "alibaba-cloud",
    name: "Alibaba Cloud",
    displayName: "Alibaba Cloud",
    providerType: "hyperscaler",
    reliabilityTier: "enterprise",
    websiteUrl: "https://www.alibabacloud.com",
    pricingUrl: "https://www.alibabacloud.com/pricing",
    docsUrl: "https://www.alibabacloud.com/help",
    hasPublicApi: true,
    supportsReserved: true,
  },
  {
    slug: "tencent-cloud",
    name: "Tencent Cloud",
    displayName: "Tencent Cloud",
    providerType: "hyperscaler",
    reliabilityTier: "enterprise",
    websiteUrl: "https://www.tencentcloud.com",
    pricingUrl: "https://www.tencentcloud.com/pricing",
    docsUrl: "https://www.tencentcloud.com/document",
    hasPublicApi: true,
    supportsReserved: true,
  },
  {
    slug: "huawei-cloud",
    name: "Huawei Cloud",
    displayName: "Huawei Cloud",
    providerType: "hyperscaler",
    reliabilityTier: "enterprise",
    websiteUrl: "https://www.huaweicloud.com",
    pricingUrl: "https://www.huaweicloud.com/intl/en-us/pricing",
    docsUrl: "https://support.huaweicloud.com/intl/en-us",
    hasPublicApi: true,
    supportsReserved: true,
  },
  {
    slug: "baidu-cloud",
    name: "Baidu AI Cloud",
    displayName: "Baidu Cloud",
    providerType: "hyperscaler",
    reliabilityTier: "enterprise",
    websiteUrl: "https://cloud.baidu.com",
    pricingUrl: "https://cloud.baidu.com/product",
    docsUrl: "https://cloud.baidu.com/doc",
    hasPublicApi: false,
    supportsReserved: true,
  },

  {
    slug: "phoenixnap",
    name: "phoenixNAP",
    displayName: "phoenixNAP",
    providerType: "bare_metal",
    reliabilityTier: "standard",
    websiteUrl: "https://phoenixnap.com",
    pricingUrl: "https://phoenixnap.com/pricing",
    docsUrl: "https://developers.phoenixnap.com",
    hasPublicApi: false,
    supportsReserved: true,
  },
  {
    slug: "leaseweb",
    name: "Leaseweb",
    displayName: "Leaseweb",
    providerType: "bare_metal",
    reliabilityTier: "standard",
    websiteUrl: "https://www.leaseweb.com",
    pricingUrl: "https://www.leaseweb.com/pricing",
    docsUrl: "https://developer.leaseweb.com",
    hasPublicApi: false,
    supportsReserved: true,
  },
  {
    slug: "servers-com",
    name: "Servers.com",
    displayName: "Servers.com",
    providerType: "bare_metal",
    reliabilityTier: "standard",
    websiteUrl: "https://www.servers.com",
    pricingUrl: "https://www.servers.com/pricing",
    hasPublicApi: false,
    supportsReserved: true,
  },
  {
    slug: "hivelocity",
    name: "Hivelocity",
    displayName: "Hivelocity",
    providerType: "bare_metal",
    reliabilityTier: "standard",
    websiteUrl: "https://www.hivelocity.net",
    pricingUrl: "https://www.hivelocity.net/pricing/",
    hasPublicApi: false,
    supportsReserved: true,
  },

  {
    slug: "e2e-networks",
    name: "E2E Networks",
    displayName: "E2E",
    providerType: "regional_cloud",
    reliabilityTier: "standard",
    websiteUrl: "https://www.e2enetworks.com",
    pricingUrl: "https://www.e2enetworks.com/pricing",
    hasPublicApi: false,
    supportsSpot: true,
  },
  {
    slug: "acecloud",
    name: "Ace Cloud",
    displayName: "Ace Cloud",
    providerType: "regional_cloud",
    reliabilityTier: "standard",
    websiteUrl: "https://www.acecloud.in",
    pricingUrl: "https://www.acecloud.in/pricing",
    hasPublicApi: false,
  },

  {
    slug: "akash",
    name: "Akash Network",
    displayName: "Akash",
    providerType: "depin",
    reliabilityTier: "community",
    websiteUrl: "https://akash.network",
    docsUrl: "https://docs.akash.network",
    hasPublicApi: true,
    supportsSpot: true,
  },
  {
    slug: "aethir",
    name: "Aethir",
    displayName: "Aethir",
    providerType: "depin",
    reliabilityTier: "community",
    websiteUrl: "https://aethir.com",
    hasPublicApi: false,
    supportsSpot: true,
  },
  {
    slug: "clore-ai",
    name: "Clore.ai",
    displayName: "Clore.ai",
    providerType: "depin",
    reliabilityTier: "community",
    websiteUrl: "https://clore.ai",
    hasPublicApi: false,
    supportsSpot: true,
  },
  {
    slug: "golem",
    name: "Golem Network",
    displayName: "Golem",
    providerType: "depin",
    reliabilityTier: "community",
    websiteUrl: "https://golem.network",
    docsUrl: "https://docs.golem.network",
    hasPublicApi: true,
    supportsSpot: true,
  },
  {
    slug: "render-network",
    name: "Render Network",
    displayName: "Render",
    providerType: "depin",
    reliabilityTier: "community",
    websiteUrl: "https://rendernetwork.com",
    hasPublicApi: false,
    supportsSpot: true,
  },
];
